# -*- coding: utf-8 -*-
"""
Created on Mon Oct  5 18:47:16 2020

@author: 15025

draw alphabet turtle and move it from screen
"""

import turtle 


class Picture:
    def drawRectangular(self):
        obj = turtle.Turtle()
        obj.hideturtle()
        obj.color("red")
        obj.speed(10)
        obj.pensize(8)
        obj.penup()
        obj.setpos(-175,75)
        obj.pendown()
        obj.speed(1)
        obj.setpos(-125,75)
        obj.speed(8)
        obj.setpos(-150,75)
        obj.speed(1)
        obj.setpos(-150,10)
        #End of First "T"
        #Start of "U"
        obj.color("orange")
        obj.speed(10)
        obj.penup()
        obj.setpos(-100,75)
        obj.pendown()
        obj.speed(1)
        obj.setpos(-100,10)
        obj.setpos(-60,10)
        obj.setpos(-60,75)
        #End of "U"
        #Start of "R"
        obj.color("yellow")
        obj.penup()
        obj.speed(10)
        obj.setpos(-30,10)
        obj.pendown()
        obj.speed(1)
        obj.setpos(-30,75)
        obj.setpos(0,75)
        obj.setpos(0,45)
        obj.setpos(7,10)
        obj.speed(8)
        obj.setpos(0,45)
        obj.speed(1)
        obj.setpos(-30,45)
        #End of "R"
        #Start of Second "T"
        obj.color("green")
        obj.speed(10)
        obj.penup()
        obj.setpos(25,75)
        obj.pendown()
        obj.speed(1)
        obj.setpos(75,75)
        obj.speed(8)
        obj.setpos(50,75)
        obj.speed(1)
        obj.setpos(50,10)
        #End of Second "T"
        #Start of "L"
        obj.color("blue")
        obj.speed(10)
        obj.penup()
        obj.setpos(105,75)
        obj.pendown()
        obj.speed(1)
        obj.setpos(105,10)
        obj.setpos(135,10)
        #End of "L"
        #Start of "E"
        obj.color("indigo")
        obj.speed(8)
        obj.penup()
        obj.setpos(155,75)
        obj.pendown()
        obj.speed(1)
        obj.setpos(155,10)
        obj.speed(10)
        obj.setpos(155,75)
        obj.speed(1)
        obj.setpos(190,75)
        obj.penup()
        obj.speed(8)
        obj.setpos(155,44)
        obj.pendown()
        obj.speed(1)
        obj.setpos(190,44)
        obj.penup()
        obj.speed(8)
        obj.setpos(155,10)
        obj.pendown()
        obj.speed(1)
        obj.setpos(190,10)
        #End of "E"
        obj.color("violet")
        obj.pensize(1)
        obj.speed(8)
        obj.penup()
        obj.setpos(10,-130)
        obj.pendown()
        obj.showturtle()
        obj.shape("turtle")
        obj.speed(3)
        obj.circle(20)
        obj.circle(25)
        obj.circle(30)
        obj.circle(35)
        obj.circle(40)
        obj.circle(45)
        obj.circle(50)
        obj.circle(55)
        obj.color("black")
        obj.penup()
        obj.hideturtle()
        obj.speed(10)
        obj.setpos(-175,85)
        obj.showturtle()
        obj.speed(1)
        obj.setpos(190,85)
        obj.setpos(190,0)
        obj.setpos(-175,0)
        obj.setpos(-175,85)
        obj.hideturtle()
        obj.speed(5)
        obj.setpos(-1000, -1000)
        
        obj.pensize(40)
        obj.shape("square")
        obj.speed(6)
        obj.setpos(-190,75)
        obj.pendown()
        obj.speed(2)
        obj.color("white")
        obj.setpos(190,75)
        
        obj.speed(6)
        obj.penup()
        obj.setpos(190,35)
        obj.pendown()
        obj.speed(2)
        obj.setpos(-190,35)
        
        obj.speed(6)
        obj.penup()
        obj.setpos(-190,-5)
        obj.pendown()
        obj.speed(2)
        obj.setpos(190,-5)
        
        obj.speed(10)
        obj.penup()
        obj.setpos(190,-45)
        obj.pendown()
        obj.speed(2)
        obj.setpos(-190,-45)
        
        obj.speed(10)
        obj.penup()
        obj.setpos(-190,-85)
        obj.pendown()
        obj.speed(2)
        obj.setpos(190,-85)
        
        obj.speed(10)
        obj.penup()
        obj.setpos(190,-125)
        obj.pendown()
        obj.speed(2)
        obj.setpos(-190,-125)
        
        obj.speed(10)
        obj.penup()
        obj.setpos(-190,-165)
        obj.pendown()
        obj.speed(2)
        obj.setpos(190,-165)

        turtle.done()
        
        
if __name__ == "__main__":
    main = Picture()
    main.drawRectangular()